S-REACH/core/urls.py
from django.contrib import admin
#from library.views import home
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
]
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

S-REACH/system/models.py
from django.db import models, connection
from django.db.models import Lookup, Func
from django import forms
from rdkit import Chem


###################################################
#PostgreSQL(データベース)への検索処理を拡張実装している
#https://github.com/rdkit/django-rdkit からパクった
#ここは黒魔術パート(なんで動くか良くわかってない)
#改変してもサポートできません
###################################################

class MolField(models.Field):
    
    description = ("Molecule")

    def db_type(self, connection):
        return 'mol'

    def get_placeholder(self, value, compiler, connection):
        if hasattr(value, 'as_sql'):
            return '%s'
        else:
            return 'mol_from_pkl(%s)'

    def select_format(self, compiler, sql, params):
        return 'mol_to_pkl(%s)' % sql, params

    def from_db_value(self, value, expression, connection):
        if value is None:
            return value
        return Chem.Mol(bytes(value))

    def to_python(self, value):
        if value is None or isinstance(value, Chem.Mol):
            return value
        if isinstance(value, str):
            return self.text_to_mol(value)
        elif isinstance(value, (bytes, bytearray, memoryview)):
            return Chem.Mol(bytes(value))
        else:
            raise ValidationError("Invalid input for a Mol instance")

    def get_prep_value(self, value):
        # convert the Molecule instance to the value used by the db driver
        if isinstance(value, str):
            value = self.text_to_mol(value)
        if isinstance(value, Chem.Mol):
            value = memoryview(value.ToBinary())
        if value is None:
            return value
        return Func(value, function='mol_from_pkl')

    @staticmethod
    def text_to_mol(value):
        value = str(value)
        mol = (Chem.MolFromSmiles(value)
            or Chem.MolFromMolBlock(value)
            or Chem.inchi.MolFromInchi(value))
        if mol is None:
            raise ValidationError("Invalid input for a Mol instance")
        return value

    def get_prep_lookup(self, lookup_type, value):
        "Perform preliminary non-db specific lookup checks and conversions"
        supported_lookup_types = (
            ['hassubstruct', 'issubstruct', 'exact', 'isnull',] +
            [T.lookup_name for T in MOL_DESCRIPTOR_TRANFORMS]
        )
        if lookup_type in supported_lookup_types:
            return value
        raise TypeError("Field has invalid lookup: %s" % lookup_type)

    def formfield(self, **kwargs):
        ## Use TextField as default input form to accommodate line breaks needed for molBlocks
        defaults = {'form_class': forms.CharField, 'strip': False, 'widget':forms.Textarea}
        defaults.update(kwargs)
        return None
        super().formfield(**defaults)

class HasSubstruct(Lookup):
    lookup_name = 'hassubstruct'
    prepare_rhs = False

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        return "%s @> %s ::qmol" % (lhs, rhs), params

        return "%s @>mol_adjust_query_properties(%s, '{\"makeDummiesQueries \":false;\"adjustDegree\":false;}')" % (lhs, rhs), params

class NotEqual(Lookup):
    lookup_name = 'ne'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        return '%s <> %s ::qmol' % (lhs, rhs), params

class IsEqual(Lookup):
    lookup_name = 'isequal'
    prepare_rhs = False

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        return '%s @= %s' % (lhs, rhs), params

MolField.register_lookup(HasSubstruct)
MolField.register_lookup(NotEqual)
MolField.register_lookup(IsEqual)

###################################################
#黒魔術ここまで
###################################################

###################################################
#続いてデータベースの構造(列の名前とか)について
# <列の名前> = models.<データ型>(
#     <オプション>(下記参照)
# )
#データ型は
#   1行程度の文字列：CharField
#   複数行の文字列： TextField
#   数値：          FloatField
#   ファイル：       FileField
#から選択すればいいと思います。
#
#変更した場合、
#       manage.py makemigrations
#       manage.py migrate
#を実行してください。
#※列を削除した場合、列の名前を変更した場合はデータが消失します
###################################################

class Inventry(models.Model):
    smiles     = models.CharField( verbose_name='SMILES*', max_length=1000,)
    expdata    = models.TextField( verbose_name='コード*', max_length=1000,)

    #以下は任意で入力可能な項目
    name       = models.CharField( null=True, blank=True, verbose_name='製品名', max_length=1000)
    seller     = models.CharField( null=True, blank=True, verbose_name='卸業者', max_length=1000)
    properties = models.TextField( null=True, blank=True, verbose_name='性状',   max_length=1000)
    comments   = models.TextField( null=True, blank=True, verbose_name='その他', max_length=1000)
    HNMR       = models.FileField( null=True, blank=True, verbose_name='1H NMR', upload_to='',)
    CNMR       = models.FileField( null=True, blank=True, verbose_name='13C NMR',upload_to='',)
    IR         = models.FileField( null=True, blank=True, verbose_name='IR',     upload_to='',)
    UV_vis     = models.FileField( null=True, blank=True, verbose_name='UV_vis', upload_to='',)
    XRD        = models.FileField( null=True, blank=True, verbose_name='XRD',    upload_to='',)
    mol        = MolField(         null=True, blank=True,                        db_index=True)#分子構造を保持するための特別な列、上の方で定義している
    mw         = models.FloatField(null=True, blank=True,                        db_index=True)#分子量を保持する
    
    def save(self, *args, **kwargs):
        super(Inventry, self).save(*args, **kwargs)
        with connection.cursor() as cursor:

            #mol列(分子構造を持つ列)が空のときに、分子構造を注入する。
            #構造はSMILES列から取得する。
            cursor.execute("UPDATE system_inventry SET mol=mol_from_smiles(smiles::cstring) where mol is null")

            #分子量を計算し、検索を高速化するおまじないをかける。
            cursor.execute("UPDATE system_inventry SET mw=mol_amw(mol) where mw is null")
            #cursor.execute("create index on library_inventry using gist(mol);")

class Bottle(models.Model):
    compound = models.ForeignKey(  Inventry ,verbose_name='comBB',    on_delete=models.PROTECT,)
    lot_No   = models.CharField(             verbose_name='Lot No.',  max_length=1000, null=True, blank=True,  )
    ordered  = models.BooleanField(          verbose_name='注文済み', default=False,)
    delivered= models.BooleanField(          verbose_name='納品済み', default=False,)

S-REACH/templates/base.html
<!doctype html>
<html lang="ja">{% load static %}
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" language="javascript" src="{% static '/jsme.nocache.js' %}"></script>
    <script>
        //this function will be called after the JavaScriptApplet code has been loaded.
        function jsmeOnLoad() {
            //Instantiate a new JSME:
            //arguments: HTML id, width, height (must be string not number!)

            jsmeApplet = new JSApplet.JSME("appletContainer", "600px", "440px", {
                //optional parameters
                "smiles":"{% block smiles %}{% endblock %}"
            });
            document.JME = jsmeApplet;
            document.getElementById("inchiKeyUrlTextArea").value = jsmeApplet.getWebSearchInchiKeyBaseUrl();
        }
        function getSmiles() {
            document.forms.form1.smiles.value = document.JME.smiles();
            var f = document.forms["form1"];
            f.method = "POST"; 
            f.submit();
            return false;
        }
    </script>
    <link rel="stylesheet" href="{% static 'css/library.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
</head>

<body>
    <div class="header">
        <a href="/search/" {% block manu_s %}{% endblock %}>検索画面</a><a href="/create/" {% block manu_c %}{% endblock %}>登録画面</a><a href="/admin/"  {% block manu_a %}{% endblock %}>管理者</a>
    </div>
    <div class="container">
{% block container %}{% endblock %}
    </div>
</body>
</html>

S-REACH/templates/create.html
{% extends "base.html" %}
{% block title %}登録画面{% endblock %}
{% block smiles %}{% if form.smiles.value %}{{form.smiles.value}}{%endif%}{% endblock %}
{% block manu_c %}class="select"{% endblock %}
{% block container %}
        <div id="appletContainer"></div>
        <form name="form1" action="/create/" method="post" class="nomargin" enctype="multipart/form-data" autocomplete="off"> 
            {% for error in form.smiles.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
            {% csrf_token %}
            <div class="from_table">
                <div class="field">
                    <div >{{ form.name.label_tag }}</div>
                    <div >
                        {{ form.name }}
                        {% if form.name.help_text %}<span class="helptext">{{ form.name.help_text }}</span>{% endif %}
                        {% for error in form.name.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field" style="display: none;">
                    <div >{{ form.smiles.label_tag }}</div>
                    <div >
                        {{ form.smiles }}
                        {% if form.smiles.help_text %}<span class="helptext">{{ form.smiles.help_text }}</span>{% endif %}
                        {% for error in form.smiles.errors %}<span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.expdata.label_tag }}</div>
                    <div >
                        {{ form.expdata }}
                        {% if form.expdata.help_text %}<span class="helptext">{{ form.expdata.help_text }}</span>{% endif %}
                        {% for error in form.expdata.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.seller.label_tag }}</div>
                    <div >
                        {{ form.seller }}
                        {% if form.seller.help_text %}<span class="helptext">{{ form.seller.help_text }}</span>{% endif %}
                        {% for error in form.seller.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.properties.label_tag }}</div>
                    <div >
                        {{ form.properties }}
                        {% if form.properties.help_text %}<span class="helptext">{{ form.properties.help_text }}</span>{% endif %}
                        {% for error in form.properties.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.HNMR.label_tag }}</div>
                    <div >
                        {{ form.HNMR }}
                        {% if form.HNMR.help_text %}<span class="helptext">{{ form.HNMR.help_text }}</span>{% endif %}
                        {% for error in form.HNMR.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.CNMR.label_tag }}</div>
                    <div >
                        {{ form.CNMR }}
                        {% if form.CNMR.help_text %}<span class="helptext">{{ form.CNMR.help_text }}</span>{% endif %}
                        {% for error in form.CNMR.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.IR.label_tag }}</div>
                    <div >
                        {{ form.IR }}
                        {% if form.IR.help_text %}<span class="helptext">{{ form.IR.help_text }}</span>{% endif %}
                        {% for error in form.IR.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.UV_vis.label_tag }}</div>
                    <div >
                        {{ form.UV_vis }}
                        {% if form.UV_vis.help_text %}<span class="helptext">{{ form.UV_vis.help_text }}</span>{% endif %}
                        {% for error in form.UV_vis.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.comments.label_tag }}</div>
                    <div >
                        {{ form.comments }}
                        {% if form.comments.help_text %}<span class="helptext">{{ form.comments.help_text }}</span>{% endif %}
                        {% for error in form.comments.errors %}<br><span class="errortext">↑{{ error }}</span>{% endfor %}
                    </div>
                </div>
            </div>
            {% if form.duplicate_allow.errors %}
                    {{ form.duplicate_allow }}化合物が重複することを許可する
                    {% if form.duplicate_allow.help_text %}<span class="helptext">{{ form.duplicate_allow.help_text|linebreaksbr }}</span>{% endif %}
                    {% for error in form.duplicate_allow.errors %}<br>{{ error|linebreaksbr }}{% endfor %}
                    <br>
            {% endif %}
        </form>
        <button type="button" onclick='getSmiles();'>登録</button>

        
        {%if form.result_smiles%}
        <hr>
        <h3>重複している分子</h3>
        {% endif %}
        <div class="result_table">
            {% for item in form.result_smiles %}
            <div class="result_table_row">
                <div code="JME.class" archive="JME.jar" width="200px" height="200px" style="display:table-cell;border-top: 1px gray solid;">
                    <param name="options" value="depict,useopenchemlib">
                    <param name="smiles"  value="{{ item.smiles}}">
                </div>
                
                <div class="result_detail">
                    {%if item.name %}<h3>{{item.name}}</h3>{% endif %}
                    <table>
                        <tr><td>コード：</td><td>{{ item.expdata | linebreaksbr}}</td></tr>
                        {%if item.HNMR   %}<tr><td>HNMR   ：</td><td>{{ item.HNMR}}</td></tr>{% endif %}
                        {%if item.CNMR   %}<tr><td>CNMR   ：</td><td>{{ item.CNMR}}</td></tr>{% endif %}
                        {%if item.IR     %}<tr><td>IR     ：</td><td>{{ item.IR  }}</td></tr>{% endif %}
                        {%if item.UV_vis %}<tr><td>UV_vis ：</td><td>{{ item.UV_vis}}</td></tr>{% endif %}
                    </table>
                    <a class="gotoEdit" href="/update/{{item.id}}">編集画面へ</a>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

S-REACH/templates/order.html
{% extends "base.html" %}
{% block title %}編集画面{%if form.name.value%}:{{ form.name.value }}{%endif%}{% endblock %}
{% if form.smiles.value %}{% block smiles %}{{ Inventry.smiles }}{% endblock %}{%endif%}
{% block manu_s %}class="select"{% endblock %}
{% block container %}
        <div id="appletContainer"></div>
        <form name="form1" action="" method="post" enctype="multipart/form-data" class="nomargin" autocomplete="off"> 
            {% csrf_token %}

            {% for error in form.smiles.errors %}<br>↑{{ error }}{% endfor %}
            <div class="from_table">
                <div class="field">
                    <div>{{ form.counter.label_tag }}</div>
                    <div>
                        {{ form.counter }}
                        {% if form.name.help_text %}<span class="helptext">{{ form.name.help_text }}</span>{% endif %}
                        {% for error in form.name.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field" style="display: none;">
                    <div ></div>
                    <div>
                        {{ form.smiles }}{{ Inventry.mw }}
                        {% if form.smiles.help_text %}<span class="helptext">{{ form.smiles.help_text }}</span>{% endif %}
                        {% for error in form.smiles.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field" style="display: none;">
                    <div ></div>
                    <div>
                    <input name="compound" value="{{id}}" required="" id="id_compound">
                    </div>
                </div>
                
            </div>
        <button>発注</button>
        </form>

{% endblock %}

S-REACH/templates/result.html
{% extends "base.html" %}
{% block title %}検索結果：{{ object_list | length }}件{% endblock %}
{% block smiles %}{{ test_form.smiles.value }}{% endblock %}
{% block manu_s %}class="select"{% endblock %}
{% block container %}
    <div id="appletContainer"></div>
    <form name="form1" action="/result/" method="post"> {% csrf_token %}
        <input type="hidden" name="smiles" value="">
        製品名:<input type="text" name="name" maxlength="1000" id="id_name" autocomplete="off" value="{{ test_form.name.value}}"><br>
        実験者:<input type="text" name="expdata" maxlength="1000" id="id_user" autocomplete="off" value="{{ test_form.expdata.value}}">
    </form>
    <button type="button" onclick='getSmiles();'>検索</button>
    <p>検索結果：{{ object_list | length }}件</p>
    <div class="result_table">
    {% for item in object_list %}
        <div class="result_table_row">
            <div code="JME.class" archive="JME.jar" width="200px" height="200px" style="position:relative;display:table-cell;border-top: 1px gray solid;">
                <param name="options" value="depict,useopenchemlib">
                <param name="smiles" value="{{ item.smiles}}">
            </div>
            <div class="result_detail">
                {%if item.name %}<h3>{{item.name}}</h3>{% endif %}
                <table>
                <tr><td>コード：</td><td>{{ item.expdata | linebreaksbr}}</td></tr>
                </table>
                <span class="gotoEdit">
                <a  href="/order/{{item.id}}">発注画⾯へ</a><br>
                <a  href="/update/{{item.id}}">編集画⾯へ</a></span>
            </div>
        </div>
{% endfor %}
</div>
</div>
{% endblock %}

S-REACH/templates/search.html
{% extends "base.html" %}
{% block title %}検索画面{% endblock %}
{% block manu_s %}class="select"{% endblock %}
{% block container %}
        <div id="appletContainer"></div>
        <form name="form1" action="/result/" method="post"> {% csrf_token %}
            <input type="hidden" name="smiles" value="">
            製品名:<input type="text" name="name" maxlength="1000" id="id_name" autocomplete="off"><br>
            コード:<input type="text" name="expdata" maxlength="1000" id="id_name" autocomplete="off">
        </form>
        <button type="button" onclick='getSmiles();'>検索</button>{{form}}
{% endblock %}

S-REACH/templates/sellerOrder.html
<!doctype html>
<html lang="ja">{% load static %}
<head>
    <meta charset="utf-8">
    <title>検索結果：{{ object_list | length }}件</title>
    <script type="text/javascript" language="javascript" src="{% static '/jsme.nocache.js' %}"></script>
    <script>
        //this function will be called after the JavaScriptApplet code has been loaded.
        function jsmeOnLoad() {
            // glutathione
            //Instantiate a new JSME:
            //arguments: HTML id, width, height (must be string not number!)

            jsmeApplet = new JSApplet.JSME("appletContainer", "600px", "440px", {
                //optional parameters
                "options": "query,hydrogens,fullScreenIcon",
                "smiles":"{{ test_form.smiles.value}}"
            });
            document.JME = jsmeApplet;
            document.getElementById("inchiKeyUrlTextArea").value = jsmeApplet.getWebSearchInchiKeyBaseUrl();
        }
        function getSmiles() {
            document.forms.form1.smiles.value = document.JME.smiles();
            var f = document.forms["form1"];
            f.method = "POST"; 
            f.submit();
            return false;
        }
    </script>
    <link rel="stylesheet" href="{% static 'css/library.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
</head>

<body>
    <div class="header">
        <a href="/search/" class="select">検索画面</a><a href="/create/">登録画面</a><a href="/admin/">管理者</a>
    </div>
    <div class="container">
        <form name="form1" action="/result/" method="post"> {% csrf_token %}
            <input type="hidden" name="smiles" value="">
            製品名:<input type="text" name="name" maxlength="1000" id="id_name" autocomplete="off" value="{{ test_form.name.value}}"><br>
            実験者:<input type="text" name="expdata" maxlength="1000" id="id_user" autocomplete="off" value="{{ test_form.expdata.value}}">
        </form>
        <button type="button" onclick='getSmiles();'>検索</button>
        
        <p>検索結果：{{ object_list | length }}件</p>
        <table>
        {% for item in object_list %}
            <tr><td>{{item.id}}</td><td>{{item.compound__smiles}}</td><td>{{item.total}}</td></tr>
        {% endfor %}
        </table>>

    </div>

</body>
</html>

S-REACH/templates/update.html
{% extends "base.html" %}
{% block title %}編集画面{%if form.name.value%}:{{ form.name.value }}{%endif%}{% endblock %}
{% if form.smiles.value %}{% block smiles %}{{ form.smiles.value}}{% endblock %}{%endif%}
{% block manu_s %}class="select"{% endblock %}
{% block container %}
        <div id="appletContainer"></div>
        <form name="form1" action="" method="post" enctype="multipart/form-data" class="nomargin" autocomplete="off"> 
            {% csrf_token %}

            {% for error in form.smiles.errors %}<br>↑{{ error }}{% endfor %}
            <div class="from_table">
                <div class="field">
                    <div>{{ form.name.label_tag }}</div>
                    <div>
                        {{ form.name }}
                        {% if form.name.help_text %}<span class="helptext">{{ form.name.help_text }}</span>{% endif %}
                        {% for error in form.name.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field" style="display: none;">
                    <div >{{ form.smiles.label_tag }}</div>
                    <div>
                        {{ form.smiles }}
                        {% if form.smiles.help_text %}<span class="helptext">{{ form.smiles.help_text }}</span>{% endif %}
                        {% for error in form.smiles.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div>{{ form.expdata.label_tag }}</div>
                    <div>
                        {{ form.expdata }}
                        {% if form.expdata.help_text %}<span class="helptext">{{ form.expdata.help_text }}</span>{% endif %}
                        {% for error in form.expdata.errors %}<br>↑{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div>{{ form.seller.label_tag }}</div>
                    <div>
                        {{ form.seller }}
                        {% if form.seller.help_text %}<span class="helptext">{{ form.seller.help_text }}</span>{% endif %}
                        {% for error in form.seller.errors %}<br>↑{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.properties.label_tag }}</div>
                    <div >
                        {{ form.properties }}
                        {% if form.properties.help_text %}<span class="helptext">{{ form.properties.help_text }}</span>{% endif %}
                        {% for error in form.properties.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.HNMR.label_tag }}</div>
                    <div >
                        {{ form.HNMR }}<br>
                        {{ form.CNMR }}<br>
                        {{ form.IR }}<br>
                        {{ form.UV_vis }}<br>
                        {% if form.HNMR.help_text %}<span class="helptext">{{ form.HNMR.help_text }}</span>{% endif %}
                        {% for error in form.HNMR.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div >{{ form.comments.label_tag }}</div>
                    <div >
                        {{ form.comments }}<br>
                        {% if form.comments.help_text %}<span class="helptext">{{ form.comments.help_text }}</span>{% endif %}
                        {% for error in form.comments.errors %}<br>{{ error }}{% endfor %}
                    </div>
                </div>
            </div>
        </form>
        <button type="button" onclick='getSmiles();'>登録</button>

{% endblock %}